[[module.imports]]
path = "github.com/razonyang/hb-header"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons-bootstrap"

[params.hugopress.modules.hb-header-theme-toggle.attributes.document]

[params.hugopress.modules.hb-header-theme-toggle.hooks.hb-header-panel]
