[[module.imports]]
path = "github.com/razonyang/hb-header"

[[module.imports]]
path = "github.com/razonyang/hb-search"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons-bootstrap"

[params.hugopress.modules.hb-header-search.hooks.hb-header-togglers-begin]
